package com.zhhl.android.policemovecareful;

import java.util.ArrayList;

/**
 * Created by miao on 2019/1/11.
 */
public class SoapContent {

    public static String GZL(String condition) {
        return "<v:Envelope xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:d=\"http://www.w3.org/2001/XMLSchema\" xmlns:c=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:v=\"http://schemas.xmlsoap.org/soap/envelope/\"><v:Header /><v:Body> <QueryService xmlns=\"http://server.tcwebservice.tc.com\" id=\"o0\" c:root=\"1\"><Blob i:type=\"d:string\">&lt;?xml version= \"1.0\" encoding= \"GB2312\"?&gt;&lt;RBSPMessage&gt;&lt;RequesterID&gt;C-ZHHLYDSP-001&lt;/RequesterID&gt;&lt;Method&gt; &lt;Name&gt; QueryServiceRequest &lt;/Name&gt; &lt;Security&gt; &lt;Signature/&gt; &lt;Encrypt Algorithm=\"\"/&gt; &lt;/Security&gt; &lt;Items&gt; &lt;Item&gt; &lt;Name&gt;  SysAlias &lt;/Name&gt; &lt;Value Type=\"string \"&gt;  &lt;Data&gt;  DSjwzhxt  &lt;/Data&gt; &lt;/Value&gt; &lt;/Item&gt; &lt;Item&gt; &lt;Name&gt;  DataObjectCode &lt;/Name&gt; &lt;Value Type=\"string \"&gt;  &lt;Data&gt;C-GZL-001&lt;/Data&gt; &lt;/Value&gt; &lt;/Item&gt; &lt;Item&gt; &lt;Name&gt;Condition&lt;/Name&gt; &lt;Value Type=\"string \"&gt;  &lt;Data&gt;  &lt;![CDATA[" + condition + "]]&gt;  &lt;/Data&gt; &lt;/Value&gt; &lt;/Item&gt; &lt;Item&gt; &lt;Name&gt;Pager &lt;/Name&gt; &lt;Value Type=\"string \"&gt;  &lt;Row&gt;  &lt;Data&gt;1&lt;/Data&gt;  &lt;Data&gt;" + (DefaultConfig.ALL ? 10 : 100) + "&lt;/Data&gt;  &lt;/Row&gt; &lt;/Value&gt; &lt;/Item&gt; &lt;Item&gt; &lt;Name&gt;RequiredItems&lt;/Name&gt; &lt;Value Type=\"arrayOf_string \"&gt;  &lt;Row&gt;  &lt;Data&gt;ID&lt;/Data&gt;  &lt;Data&gt;TOPIC&lt;/Data&gt;  &lt;Data&gt;CONTENT&lt;/Data&gt;&lt;Data&gt;MSGTYPE&lt;/Data&gt;  &lt;Data&gt;MSGSTATE&lt;/Data&gt;  &lt;Data&gt;DEVTYPE&lt;/Data&gt;  &lt;Data&gt;SENDTO&lt;/Data&gt;  &lt;Data&gt;SENDFROM&lt;/Data&gt;  &lt;Data&gt;SENDTODATE&lt;/Data&gt;  &lt;/Row&gt; &lt;/Value&gt; &lt;/Item&gt; &lt;/Items&gt;&lt;/Method&gt;&lt;/RBSPMessage&gt;</Blob></QueryService></v:Body></v:Envelope>";
    }

    public static String WSBH(String id) {
        return "<v:Envelope xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:d=\"http://www.w3.org/2001/XMLSchema\" xmlns:c=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:v=\"http://schemas.xmlsoap.org/soap/envelope/\"><v:Header /><v:Body><QueryService xmlns=\"http://server.tcwebservice.tc.com\" id=\"o0\" c:root=\"1\"><Blob i:type=\"d:string\">&lt;?xml version= \"1.0\" encoding= \"GB2312\"?&gt;&lt;RBSPMessage&gt;&lt;RequesterID&gt;C-ZHHLYDSP-001&lt;/RequesterID&gt;&lt;Method&gt; &lt;Name&gt; QueryService &lt;/Name&gt; &lt;Security&gt; &lt;Signature/&gt; &lt;Encrypt Algorithm=\" \"/&gt; &lt;/Security&gt; &lt;Items&gt; &lt;Item&gt; &lt;Name&gt;  SysAlias &lt;/Name&gt; &lt;Value Type=\"string \"&gt;  &lt;Data&gt;  DSjwzhxt  &lt;/Data&gt; &lt;/Value&gt; &lt;/Item&gt; &lt;Item&gt; &lt;Name&gt;  DataObjectCode &lt;/Name&gt; &lt;Value Type=\"string \"&gt;  &lt;Data&gt;  C-GZL-001,A-SPXX-001,A-SADJB-001,A-CQBGS-001  &lt;/Data&gt; &lt;/Value&gt; &lt;/Item&gt; &lt;Item&gt; &lt;Name&gt;Condition&lt;/Name&gt; &lt;Value Type=\"string \"&gt;  &lt;Data&gt;&lt;![CDATA[A-SPXX-001.AJSPWSBH = substr(trim(C-GZL-001.TOPIC),1,23) and C-GZL-001.ID='" + id + "' and A-SADJB-001.CZBS&lt;'3' and A-SPXX-001.CZBS&lt;'3' and A-SPXX-001.AJBH = A-SADJB-001.AJBH and ( A-SPXX-001.AJSPWSBH = A-CQBGS-001.ZJ OR A-SPXX-001.AJSPWSBH = A-SADJB-001.ZJ)]]&gt;  &lt;/Data&gt; &lt;/Value&gt; &lt;/Item&gt; &lt;Item&gt; &lt;Name&gt;Pager &lt;/Name&gt; &lt;Value Type=\"string \"&gt;  &lt;Row&gt;  &lt;Data&gt;1&lt;/Data&gt;  &lt;Data&gt;10&lt;/Data&gt;  &lt;/Row&gt; &lt;/Value&gt; &lt;/Item&gt; &lt;Item&gt; &lt;Name&gt;RequiredItems&lt;/Name&gt; &lt;Value Type=\"arrayOf_string \"&gt;  &lt;Row&gt;  &lt;Data&gt;A-SADJB-001.WSBH&lt;/Data&gt;  &lt;/Row&gt; &lt;/Value&gt; &lt;/Item&gt; &lt;/Items&gt;&lt;/Method&gt;&lt;/RBSPMessage&gt;</Blob></QueryService></v:Body></v:Envelope>";
    }

    public static String WSNR(ArrayList<String> wsbhs) {
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < wsbhs.size(); i++) {
            builder.append("'").append(wsbhs.get(i)).append("'");
            if (i != wsbhs.size() - 1) {
                builder.append(",");
            }
        }

        return "<v:Envelope xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:d=\"http://www.w3.org/2001/XMLSchema\" xmlns:c=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:v=\"http://schemas.xmlsoap.org/soap/envelope/\"><v:Header /><v:Body><QueryService xmlns=\"http://server.tcwebservice.tc.com\" id=\"o0\" c:root=\"1\"><Blob i:type=\"d:string\">&lt;?xml version= \"1.0\" encoding= \"GB2312\"?&gt;&lt;RBSPMessage&gt;&lt;RequesterID&gt;C-ZHHLYDSP-001&lt;/RequesterID&gt;&lt;Method&gt;&lt;Name&gt;QueryService&lt;/Name&gt;&lt;Security&gt;&lt;Signature/&gt;&lt;Encrypt Algorithm=\" \"/&gt;&lt;/Security&gt;&lt;Items&gt;&lt;Item&gt;&lt;Name&gt;SysAlias&lt;/Name&gt;&lt;Value Type=\"string \"&gt;&lt;Data&gt;DSjwzhxt&lt;/Data&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;DataObjectCode&lt;/Name&gt;&lt;Value Type=\"string \"&gt;&lt;Data&gt;A-FLWS-001&lt;/Data&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;Condition&lt;/Name&gt;&lt;Value Type=\"string \"&gt;&lt;Data&gt;&lt;![CDATA[  A-FLWS-001.FLWSBH in  (" + builder.toString() + ")  and SFYX='1' and CZBS&lt;'3']]&gt;&lt;/Data&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;Pager&lt;/Name&gt;&lt;Value Type=\"string \"&gt;&lt;Row&gt;&lt;Data&gt;1&lt;/Data&gt;&lt;Data&gt;10&lt;/Data&gt;&lt;/Row&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;RequiredItems&lt;/Name&gt;&lt;Value Type=\"arrayOf_string \"&gt;&lt;Row&gt;&lt;Data&gt;WSNR&lt;/Data&gt;&lt;/Row&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;/Items&gt;&lt;/Method&gt;&lt;/RBSPMessage&gt;</Blob></QueryService></v:Body></v:Envelope>";
    }

    public static String WSNR_COUNT(ArrayList<String> wsbhs) {
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < wsbhs.size(); i++) {
            builder.append("'").append(wsbhs.get(i)).append("'");
            if (i != wsbhs.size() - 1) {
                builder.append(",");
            }
        }

        return "<v:Envelope xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:d=\"http://www.w3.org/2001/XMLSchema\" xmlns:c=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:v=\"http://schemas.xmlsoap.org/soap/envelope/\"><v:Header /><v:Body><QueryService xmlns=\"http://server.tcwebservice.tc.com\" id=\"o0\" c:root=\"1\"><Blob i:type=\"d:string\">&lt;?xml version= \"1.0\" encoding= \"GB2312\"?&gt;&lt;RBSPMessage&gt;&lt;RequesterID&gt;C-ZHHLYDSP-001&lt;/RequesterID&gt;&lt;Method&gt;&lt;Name&gt;QueryService&lt;/Name&gt;&lt;Security&gt;&lt;Signature/&gt;&lt;Encrypt Algorithm=\" \"/&gt;&lt;/Security&gt;&lt;Items&gt;&lt;Item&gt;&lt;Name&gt;SysAlias&lt;/Name&gt;&lt;Value Type=\"string \"&gt;&lt;Data&gt;DSjwzhxt&lt;/Data&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;DataObjectCode&lt;/Name&gt;&lt;Value Type=\"string \"&gt;&lt;Data&gt;A-FLWS-001&lt;/Data&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;Condition&lt;/Name&gt;&lt;Value Type=\"string \"&gt;&lt;Data&gt;&lt;![CDATA[  A-FLWS-001.FLWSBH in  (" + builder.toString() + ")  and SFYX='1' and CZBS&lt;'3']]&gt;&lt;/Data&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;Pager&lt;/Name&gt;&lt;Value Type=\"string \"&gt;&lt;Row&gt;&lt;Data&gt;1&lt;/Data&gt;&lt;Data&gt;10&lt;/Data&gt;&lt;/Row&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;RequiredItems&lt;/Name&gt;&lt;Value Type=\"arrayOf_string \"&gt;&lt;Row&gt;&lt;Data&gt;COUNT(*)&lt;/Data&gt;&lt;/Row&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;/Items&gt;&lt;/Method&gt;&lt;/RBSPMessage&gt;</Blob></QueryService></v:Body></v:Envelope>";
    }

    public static String XZCFBGS(String id) {
        return "<v:Envelope xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:d=\"http://www.w3.org/2001/XMLSchema\" xmlns:c=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:v=\"http://schemas.xmlsoap.org/soap/envelope/\"><v:Header /><v:Body><QueryService xmlns=\"http://server.tcwebservice.tc.com\" id=\"o0\" c:root=\"1\"><Blob i:type=\"d:string\">&lt;?xml version= \"1.0\" encoding= \"GB2312\"?&gt;&lt;RBSPMessage&gt;&lt;RequesterID&gt;C-ZHHLYDSP-001&lt;/RequesterID&gt;&lt;Method&gt;&lt;Name&gt;QueryService&lt;/Name&gt;&lt;Security&gt;&lt;Signature/&gt;&lt;Encrypt Algorithm=\" \"/&gt;&lt;/Security&gt;&lt;Items&gt;&lt;Item&gt;&lt;Name&gt;SysAlias&lt;/Name&gt;&lt;Value Type=\"string \"&gt;&lt;Data&gt;DSjwzhxt&lt;/Data&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;DataObjectCode&lt;/Name&gt;&lt;Value Type=\"string \"&gt;&lt;Data&gt;C-GZL-001,A-FLWS-001,A-CQBGS-001&lt;/Data&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;Condition&lt;/Name&gt;&lt;Value Type=\"string \"&gt;&lt;Data&gt; &lt;![CDATA[ A-FLWS-001.flwsbh = A-CQBGS-001.wsbh and  substr(trim(C-GZL-001.topic) ,1,23)=A-CQBGS-001.ZJ and A-CQBGS-001.czbs &lt;'3'  and A-FLWS-001.czbs&lt;'3' and A-FLWS-001.sfyx='1' and C-GZL-001.ID='" + id + "' ]]&gt;&lt;/Data&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;Pager&lt;/Name&gt;&lt;Value Type=\"string \"&gt;&lt;Row&gt;&lt;Data&gt;1&lt;/Data&gt;&lt;Data&gt;1&lt;/Data&gt;&lt;/Row&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;RequiredItems&lt;/Name&gt;&lt;Value Type=\"arrayOf_string \"&gt;&lt;Row&gt;&lt;Data&gt;A-FLWS-001.WSNR&lt;/Data&gt;&lt;/Row&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;/Items&gt;&lt;/Method&gt;&lt;/RBSPMessage&gt;</Blob></QueryService></v:Body></v:Envelope>";
    }

    public static String XZCFBGS_COUNT(String id) {
        return "<v:Envelope xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:d=\"http://www.w3.org/2001/XMLSchema\" xmlns:c=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:v=\"http://schemas.xmlsoap.org/soap/envelope/\"><v:Header /><v:Body><QueryService xmlns=\"http://server.tcwebservice.tc.com\" id=\"o0\" c:root=\"1\"><Blob i:type=\"d:string\">&lt;?xml version= \"1.0\" encoding= \"GB2312\"?&gt;&lt;RBSPMessage&gt;&lt;RequesterID&gt;C-ZHHLYDSP-001&lt;/RequesterID&gt;&lt;Method&gt;&lt;Name&gt;QueryService&lt;/Name&gt;&lt;Security&gt;&lt;Signature/&gt;&lt;Encrypt Algorithm=\" \"/&gt;&lt;/Security&gt;&lt;Items&gt;&lt;Item&gt;&lt;Name&gt;SysAlias&lt;/Name&gt;&lt;Value Type=\"string \"&gt;&lt;Data&gt;DSjwzhxt&lt;/Data&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;DataObjectCode&lt;/Name&gt;&lt;Value Type=\"string \"&gt;&lt;Data&gt;C-GZL-001,A-FLWS-001,A-CQBGS-001&lt;/Data&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;Condition&lt;/Name&gt;&lt;Value Type=\"string \"&gt;&lt;Data&gt; &lt;![CDATA[ A-FLWS-001.flwsbh = A-CQBGS-001.wsbh and  substr(trim(C-GZL-001.topic) ,1,23)=A-CQBGS-001.ZJ and A-CQBGS-001.czbs &lt;'3'  and A-FLWS-001.czbs&lt;'3' and A-FLWS-001.sfyx='1' and C-GZL-001.ID='" + id + "' ]]&gt;&lt;/Data&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;Pager&lt;/Name&gt;&lt;Value Type=\"string \"&gt;&lt;Row&gt;&lt;Data&gt;1&lt;/Data&gt;&lt;Data&gt;1&lt;/Data&gt;&lt;/Row&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;RequiredItems&lt;/Name&gt;&lt;Value Type=\"arrayOf_string \"&gt;&lt;Row&gt;&lt;Data&gt;COUNT(*)&lt;/Data&gt;&lt;/Row&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;/Items&gt;&lt;/Method&gt;&lt;/RBSPMessage&gt;</Blob></QueryService></v:Body></v:Envelope>";
    }

    public static String AJJBXX(String startDate, String endDate, String anJianMingCheng, String anJianZhuangTai, int pager) {
        return "<v:Envelope xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:d=\"http://www.w3.org/2001/XMLSchema\" xmlns:c=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:v=\"http://schemas.xmlsoap.org/soap/envelope/\"><v:Header /><v:Body><QueryService xmlns=\"http://server.tcwebservice.tc.com\" id=\"o0\" c:root=\"1\"><Blob i:type=\"d:string\">&lt;?xml version= \"1.0\" encoding= \"GB2312\"?&gt;&lt;RBSPMessage&gt;&lt;RequesterID&gt;C-ZHHLYDSP-001&lt;/RequesterID&gt;&lt;Method&gt;&lt;Name&gt;QueryServiceRequest&lt;/Name&gt;&lt;Security&gt;&lt;Signature/&gt;\r\n&lt;Encrypt Algorithm=\" \"/&gt;&lt;/Security&gt;&lt;Items&gt;&lt;Item&gt;&lt;Name&gt;SysAlias&lt;/Name&gt;&lt;Value Type=\"string\"&gt;&lt;Data&gt;DSjwzhxt&lt;/Data&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;DataObjectCode&lt;/Name&gt;\r\n&lt;Value Type=\"string\"&gt;&lt;Data&gt;A-AJJBXX-001,Z-ZDB-001&lt;/Data&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;Condition&lt;/Name&gt;\r\n&lt;Value Type=\"string\"&gt;&lt;Data&gt;&lt;![CDATA[LARQ between '" + startDate + "' and  '" + endDate + "'" + ajmc(anJianMingCheng) + "   and AJZT=Z-ZDB-001.ZDDM and Z-ZDB-001.ZDMC='案件状态'" + ajzt(anJianZhuangTai) + "   ]]&gt;&lt;/Data&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;Pager&lt;/Name&gt;&lt;Value Type=\"string\"&gt;&lt;Row&gt;&lt;Data&gt;" + pager + "&lt;/Data&gt;&lt;Data&gt;10&lt;/Data&gt;&lt;/Row&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;Item&gt;&lt;Name&gt;RequiredItems&lt;/Name&gt;&lt;Value Type=\"arrayOf_string\"&gt;&lt;Row&gt;&lt;Data&gt;A-AJJBXX-001.AJMC&lt;/Data&gt;&lt;Data&gt;A-AJJBXX-001.AJLB&lt;/Data&gt;&lt;Data&gt;A-AJJBXX-001.SLR&lt;/Data&gt;&lt;Data&gt;A-AJJBXX-001.LARQ&lt;/Data&gt;&lt;Data&gt;A-AJJBXX-001.SLDW&lt;/Data&gt;&lt;Data&gt;A-AJJBXX-001.AJBH&lt;/Data&gt;&lt;Data&gt;Z-ZDB-001.ZDZ&lt;/Data&gt;&lt;Data&gt;A-AJJBXX-001.AQZS&lt;/Data&gt;&lt;/Row&gt;&lt;/Value&gt;&lt;/Item&gt;&lt;/Items&gt;&lt;/Method&gt;&lt;/RBSPMessage&gt;</Blob></QueryService></v:Body></v:Envelope>";
    }

    private static String ajmc(String ajmc) {
        if (ajmc == null || ajmc.equals("")) return "";
        else return " and A-AJJBXX-001.AJMC like '%" + ajmc + "%'  ";
    }

    private static String ajzt(String ajzt) {
        if (ajzt == null || ajzt.equals("")) return "";
        else return " and Z-ZDB-001.ZDZ='" + ajzt + "'  ";
    }


    public static String user(String userCode) {
        String[] split = userCode.split(",");
        StringBuilder builder = new StringBuilder();
        if (split.length > 0) {
            for (int i = 0; i < split.length; i++) {
                builder.append("'").append(split[i]).append("'");
                if (i != split.length - 1) {
                    builder.append(",");
                }
            }
        } else {
            builder.append("'").append(userCode).append("'");
        }
        return "<v:Envelope xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:d=\"http://www.w3.org/2001/XMLSchema\" xmlns:c=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:v=\"http://schemas.xmlsoap.org/soap/envelope/\"><v:Header /><v:Body><QueryService xmlns=\"http://server.tcwebservice.tc.com\" id=\"o0\" c:root=\"1\"><Blob i:type=\"d:string\">&lt;?xml version= \"1.0\" encoding= \"GB2312\"?&gt;\r\n&lt;RBSPMessage&gt;\r\n    &lt;RequesterID&gt;\r\n        C-ZHHLYDSP-001\r\n    &lt;/RequesterID&gt;\r\n    &lt;Method&gt;\r\n        &lt;Name&gt;\r\n            QueryService\r\n        &lt;/Name&gt;\r\n        &lt;Security&gt;\r\n            &lt;Signature/&gt;\r\n\r\n            &lt;Encrypt Algorithm=\" \"/&gt;\r\n        &lt;/Security&gt;\r\n        &lt;Items&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;\r\n                    SysAlias\r\n                &lt;/Name&gt;\r\n                &lt;Value Type=\"string \"&gt;\r\n                    &lt;Data&gt;\r\n                        DSjwzhxt\r\n                    &lt;/Data&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;\r\n                    DataObjectCode\r\n                &lt;/Name&gt;\r\n\r\n                &lt;Value Type=\"string \"&gt;\r\n                    &lt;Data&gt;Y-YHB-001&lt;/Data&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;Condition&lt;/Name&gt;\r\n                &lt;Value Type=\"string \"&gt;\r\n                    &lt;Data&gt;\r\n&lt;![CDATA[\r\n  USER_ID in(" + builder.toString() + ")  ]]&gt;\r\n                    &lt;/Data&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;Pager\r\n                &lt;/Name&gt;\r\n                &lt;Value Type=\"string \"&gt;\r\n                    &lt;Row&gt;\r\n                        &lt;Data&gt;1&lt;/Data&gt;\r\n                        &lt;Data&gt;10&lt;/Data&gt;\r\n                    &lt;/Row&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;RequiredItems&lt;/Name&gt;\r\n                &lt;Value Type=\"arrayOf_string \"&gt;\r\n                    &lt;Row&gt;\r\n                        &lt;Data&gt;YHM&lt;/Data&gt;\r\n                        &lt;Data&gt;YHXM&lt;/Data&gt;\r\n                        &lt;Data&gt;DWDM&lt;/Data&gt;\r\n                    &lt;/Row&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n        &lt;/Items&gt;\r\n    &lt;/Method&gt;\r\n&lt;/RBSPMessage&gt;</Blob></QueryService></v:Body></v:Envelope>\r\n";
    }


    public static String APPROVE_INFO(String ajbh) {
        return "<v:Envelope xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:d=\"http://www.w3.org/2001/XMLSchema\" xmlns:c=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:v=\"http://schemas.xmlsoap.org/soap/envelope/\"><v:Header /><v:Body><QueryService xmlns=\"http://server.tcwebservice.tc.com\" id=\"o0\" c:root=\"1\"><Blob i:type=\"d:string\">&lt;?xml version= \"1.0\" encoding= \"GB2312\"?&gt;\r\n&lt;RBSPMessage&gt;\r\n    &lt;RequesterID&gt;\r\n        C-ZHHLYDSP-001\r\n    &lt;/RequesterID&gt;\r\n    &lt;Method&gt;\r\n        &lt;Name&gt;\r\n            QueryService\r\n        &lt;/Name&gt;\r\n        &lt;Security&gt;\r\n            &lt;Signature/&gt;\r\n\r\n            &lt;Encrypt Algorithm=\" \"/&gt;\r\n        &lt;/Security&gt;\r\n        &lt;Items&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;\r\n                    SysAlias\r\n                &lt;/Name&gt;\r\n                &lt;Value Type=\"string \"&gt;\r\n                    &lt;Data&gt;\r\n                        DSjwzhxt\r\n                    &lt;/Data&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;\r\n                    DataObjectCode\r\n                &lt;/Name&gt;\r\n\r\n                &lt;Value Type=\"string \"&gt;\r\n                    &lt;Data&gt;A-SPXX-001&lt;/Data&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;Condition&lt;/Name&gt;\r\n                &lt;Value Type=\"string \"&gt;\r\n                    &lt;Data&gt;\r\n&lt;![CDATA[\r\n   A-SPXX-001.AJBH='" + ajbh + "']]&gt;\r\n                    &lt;/Data&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;Pager\r\n                &lt;/Name&gt;\r\n                &lt;Value Type=\"string \"&gt;\r\n                    &lt;Row&gt;\r\n                        &lt;Data&gt;1&lt;/Data&gt;\r\n                        &lt;Data&gt;10&lt;/Data&gt;\r\n                    &lt;/Row&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;RequiredItems&lt;/Name&gt;\r\n                &lt;Value Type=\"arrayOf_string \"&gt;\r\n                    &lt;Row&gt;\r\n                        &lt;Data&gt;FLYJ&lt;/Data&gt;\r\n                        &lt;Data&gt;SPJG&lt;/Data&gt;\r\n                        &lt;Data&gt;SPYJ&lt;/Data&gt;\r\n                        &lt;Data&gt;SPRQ&lt;/Data&gt;\r\n                    &lt;/Row&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n        &lt;/Items&gt;\r\n    &lt;/Method&gt;\r\n&lt;/RBSPMessage&gt;</Blob></QueryService></v:Body></v:Envelope>\r\n";
    }

    public static String DIRECTORY(String name, String code) {
        return "<v:Envelope xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:d=\"http://www.w3.org/2001/XMLSchema\" xmlns:c=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:v=\"http://schemas.xmlsoap.org/soap/envelope/\"><v:Header /><v:Body><QueryService xmlns=\"http://server.tcwebservice.tc.com\" id=\"o0\" c:root=\"1\"><Blob i:type=\"d:string\">&lt;?xml version= \"1.0\" encoding= \"GB2312\"?&gt;\r\n&lt;RBSPMessage&gt;\r\n    &lt;RequesterID&gt;\r\n        C-ZHHLYDSP-001\r\n    &lt;/RequesterID&gt;\r\n    &lt;Method&gt;\r\n        &lt;Name&gt;\r\n            QueryService\r\n        &lt;/Name&gt;\r\n        &lt;Security&gt;\r\n            &lt;Signature/&gt;\r\n\r\n            &lt;Encrypt Algorithm=\" \"/&gt;\r\n        &lt;/Security&gt;\r\n        &lt;Items&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;\r\n                    SysAlias\r\n                &lt;/Name&gt;\r\n                &lt;Value Type=\"string \"&gt;\r\n                    &lt;Data&gt;\r\n                        DSjwzhxt\r\n                    &lt;/Data&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;\r\n                    DataObjectCode\r\n                &lt;/Name&gt;\r\n\r\n                &lt;Value Type=\"string \"&gt;\r\n                    &lt;Data&gt;Z-ZDB-001&lt;/Data&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;Condition&lt;/Name&gt;\r\n                &lt;Value Type=\"string \"&gt;\r\n                    &lt;Data&gt;\r\n&lt;![CDATA[\r\n   Z-ZDB-001.ZDMC='" + name + "' and Z-ZDB-001.ZDDM = '" + code + "']]&gt;\r\n                    &lt;/Data&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;Pager\r\n                &lt;/Name&gt;\r\n                &lt;Value Type=\"string \"&gt;\r\n                    &lt;Row&gt;\r\n                        &lt;Data&gt;1&lt;/Data&gt;\r\n                        &lt;Data&gt;10&lt;/Data&gt;\r\n                    &lt;/Row&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;RequiredItems&lt;/Name&gt;\r\n                &lt;Value Type=\"arrayOf_string \"&gt;\r\n                    &lt;Row&gt;\r\n                        &lt;Data&gt;ZDZ&lt;/Data&gt;\r\n                    &lt;/Row&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n        &lt;/Items&gt;\r\n    &lt;/Method&gt;\r\n&lt;/RBSPMessage&gt;</Blob></QueryService></v:Body></v:Envelope>\r\n";
    }

    public static String STATISTICS(String state, String start, String end) {
        return "<v:Envelope xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:d=\"http://www.w3.org/2001/XMLSchema\" xmlns:c=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:v=\"http://schemas.xmlsoap.org/soap/envelope/\"><v:Header /><v:Body><QueryService xmlns=\"http://server.tcwebservice.tc.com\" id=\"o0\" c:root=\"1\"><Blob i:type=\"d:string\">&lt;?xml version= \"1.0\" encoding= \"GB2312\"?&gt;\r\n&lt;RBSPMessage&gt;\r\n    &lt;RequesterID&gt;\r\n        C-ZHHLYDSP-001\r\n    &lt;/RequesterID&gt;\r\n    &lt;Method&gt;\r\n        &lt;Name&gt;\r\n            QueryService\r\n        &lt;/Name&gt;\r\n        &lt;Security&gt;\r\n            &lt;Signature/&gt;\r\n\r\n            &lt;Encrypt Algorithm=\" \"/&gt;\r\n        &lt;/Security&gt;\r\n        &lt;Items&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;\r\n                    SysAlias\r\n                &lt;/Name&gt;\r\n                &lt;Value Type=\"string \"&gt;\r\n                    &lt;Data&gt;\r\n                        DSjwzhxt\r\n                    &lt;/Data&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;\r\n                    DataObjectCode\r\n                &lt;/Name&gt;\r\n\r\n                &lt;Value Type=\"string \"&gt;\r\n                    &lt;Data&gt;A-AJJBXX-001,Z-ZDB-001&lt;/Data&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;Condition&lt;/Name&gt;\r\n                &lt;Value Type=\"string \"&gt;\r\n                    &lt;Data&gt;\r\n&lt;![CDATA[\r\n  Z-ZDB-001.ZDMC='案件状态' and Z-ZDB-001.ZDDM=A-AJJBXX-001.AJZT" + state(state) + date(start, end) + "]]&gt;\r\n                    &lt;/Data&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;Pager\r\n                &lt;/Name&gt;\r\n                &lt;Value Type=\"string \"&gt;\r\n                    &lt;Row&gt;\r\n                        &lt;Data&gt;1&lt;/Data&gt;\r\n                        &lt;Data&gt;10&lt;/Data&gt;\r\n                    &lt;/Row&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;RequiredItems&lt;/Name&gt;\r\n                &lt;Value Type=\"arrayOf_string \"&gt;\r\n                    &lt;Row&gt;\r\n                        &lt;Data&gt;count(*)&lt;/Data&gt;\r\n                    &lt;/Row&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n        &lt;/Items&gt;\r\n    &lt;/Method&gt;\r\n&lt;/RBSPMessage&gt;</Blob></QueryService></v:Body></v:Envelope>\r\n";
    }


    private static String state(String state) {
        if (state == null || state.equals("")) return "";
        else return " and Z-ZDB-001.ZDZ='" + state + "' ";
    }

    private static String date(String start, String end) {
        if (start != null && end != null && !start.equals("") && !end.equals(""))
            return " and A-AJJBXX-001.SLSJ between '" + start + "' and '" + end + "'  ";
        else return "";


    }

    public static String APPROVE(String source, String newTopic) {
        return "<v:Envelope xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:d=\"http://www.w3.org/2001/XMLSchema\" xmlns:c=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:v=\"http://schemas.xmlsoap.org/soap/envelope/\"><v:Header /><v:Body><ReportService xmlns=\"http://server.tcwebservice.tc.com\" id=\"o0\" c:root=\"1\"><Blob i:type=\"d:string\">&lt;?xml version=\"1.0\" encoding=\"GB2312\" ?&gt;\r\n&lt;RBSPMessage&gt;\r\n    &lt;RequesterID&gt;\r\nC-ZHHLYDSP-001    &lt;/RequesterID&gt;\r\n    &lt;Method&gt;\r\n        &lt;Name&gt;\r\n            QueryServiceRequest\r\n        &lt;/Name&gt;\r\n        &lt;Security&gt;\r\n            &lt;Signature/&gt;\r\n\r\n            &lt;Encrypt Algorithm=\"\"/&gt;\r\n        &lt;/Security&gt;\r\n        &lt;Items&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;\r\n                    SysAlias\r\n                &lt;/Name&gt;\r\n                &lt;Value Type=\"string \"&gt;\r\n                    &lt;Data&gt;\r\n                        DSjwzhxt\r\n                    &lt;/Data&gt;\r\n                &lt;/Value&gt;\r\n            &lt;/Item&gt;\r\n            &lt;Item&gt;\r\n                &lt;Name&gt;\r\n                    Recorders\r\n                &lt;/Name&gt;\r\n                &lt;Value Type=\"arrayOf_string\"&gt;\r\n                    &lt;Row state=\"u\" tablename=\"C-GZL-001\"&gt;\r\n                        &lt;Data TOPIC=\"" + newTopic + "\"&gt;\r\n\r\n                        &lt;/Data&gt;\r\n                        &lt;SqlWhere&gt;\r\n                            &lt;![CDATA[\r\n                                TOPIC='" + source + "'\r\n                            ]]&gt;\r\n                        &lt;/SqlWhere&gt;\r\n                    &lt;/Row&gt;\r\n                &lt;/Value&gt;\r\n                &lt;/Item&gt;\r\n        &lt;/Items&gt;\r\n    &lt;/Method&gt;\r\n&lt;/RBSPMessage&gt;</Blob></ReportService></v:Body></v:Envelope>\r\n";
    }
}
